### ISSUE TITLE
Errors in react-script v5 

### ISSUE THREAD

**Issue by huzaifa50** [Sparticuz/usps-webtools-promise#19]
I'm getting the following 2 error when I use this package

`ERROR in node:https Module build failed: UnhandledSchemeError: Reading from "node:https" is not handled by plugins (Unhandled scheme). Webpack supports "data:" and "file:" URIs by default. You may need an additional plugin to handle "node:" URIs.`

`ERROR in node:querystring Module build failed: UnhandledSchemeError: Reading from "node:querystring" is not handled by plugins (Unhandled scheme). Webpack supports "data:" and "file:" URIs by default. You may need an additional plugin to handle "node:" URIs.`

What could be the issue/fix?

Bellow is the whole error 

> Failed to compile.
> 
> Module build failed: UnhandledSchemeError: Reading from "node:https" is not handled by plugins (Unhandled scheme).
> Webpack supports "data:" and "file:" URIs by default.
> You may need an additional plugin to handle "node:" URIs.
> 
> ERROR in node:https
> Module build failed: UnhandledSchemeError: Reading from "node:https" is not handled by plugins (Unhandled scheme).
> Webpack supports "data:" and "file:" URIs by default.
> You may need an additional plugin to handle "node:" URIs.
>     at path-to-project/node_modules/webpack/lib/NormalModule.js:832:25
>     at Hook.eval [as callAsync] (eval at create (path-to-project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
>     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (path-to-project/node_modules/tapable/lib/Hook.js:18:14)
>     at Object.processResource (path-to-project/node_modules/webpack/lib/NormalModule.js:829:8)
>     at processResource (path-to-project/node_modules/loader-runner/lib/LoaderRunner.js:220:11)
>     at iteratePitchingLoaders (path-to-project/node_modules/loader-runner/lib/LoaderRunner.js:171:10)
>     at runLoaders (path-to-project/node_modules/loader-runner/lib/LoaderRunner.js:398:2)
>     at NormalModule._doBuild (path-to-project/node_modules/webpack/lib/NormalModule.js:819:3)
>     at NormalModule.build (path-to-project/node_modules/webpack/lib/NormalModule.js:963:15)
>     at path-to-project/node_modules/webpack/lib/Compilation.js:1371:12
>     at NormalModule.needBuild (path-to-project/node_modules/webpack/lib/NormalModule.js:1253:32)
>     at Compilation._buildModule (path-to-project/node_modules/webpack/lib/Compilation.js:1352:10)
>     at path-to-project/node_modules/webpack/lib/util/AsyncQueue.js:303:10
>     at Hook.eval [as callAsync] (eval at create (path-to-project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
>     at AsyncQueue._startProcessing (path-to-project/node_modules/webpack/lib/util/AsyncQueue.js:293:26)
>     at AsyncQueue._ensureProcessing (path-to-project/node_modules/webpack/lib/util/AsyncQueue.js:280:12)
>     at processImmediate (node:internal/timers:466:21)
> 
> ERROR in node:querystring
> Module build failed: UnhandledSchemeError: Reading from "node:querystring" is not handled by plugins (Unhandled scheme).
> Webpack supports "data:" and "file:" URIs by default.
> You may need an additional plugin to handle "node:" URIs.
>     at path-to-project/node_modules/webpack/lib/NormalModule.js:832:25
>     at Hook.eval [as callAsync] (eval at create (path-to-project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
>     at Object.processResource (path-to-project/node_modules/webpack/lib/NormalModule.js:829:8)
>     at processResource (path-to-project/node_modules/loader-runner/lib/LoaderRunner.js:220:11)
>     at iteratePitchingLoaders (path-to-project/node_modules/loader-runner/lib/LoaderRunner.js:171:10)
>     at runLoaders (path-to-project/node_modules/loader-runner/lib/LoaderRunner.js:398:2)
>     at NormalModule._doBuild (path-to-project/node_modules/webpack/lib/NormalModule.js:819:3)
>     at NormalModule.build (path-to-project/node_modules/webpack/lib/NormalModule.js:963:15)
>     at path-to-project/node_modules/webpack/lib/Compilation.js:1371:12
>     at NormalModule.needBuild (path-to-project/node_modules/webpack/lib/NormalModule.js:1253:32)
>     at Compilation._buildModule (path-to-project/node_modules/webpack/lib/Compilation.js:1352:10)
>     at path-to-project/node_modules/webpack/lib/util/AsyncQueue.js:303:10
>     at Hook.eval [as callAsync] (eval at create (path-to-project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
>     at AsyncQueue._startProcessing (path-to-project/node_modules/webpack/lib/util/AsyncQueue.js:293:26)
>     at AsyncQueue._ensureProcessing (path-to-project/node_modules/webpack/lib/util/AsyncQueue.js:280:12)
>     at processImmediate (node:internal/timers:466:21)
> 
> webpack compiled with 2 errors and 1 warning

**Comment by Sparticuz** [comment]
This package uses the node: prefix schema. See [here](https://2ality.com/2021/12/node-protocol-imports.html)
