### ISSUE TITLE
API URL error

### ISSUE THREAD

**Issue by jgarcia24n** [Sparticuz/usps-webtools-promise#3]
Request URL is showing https://secure.shippingapis.comshippingapi.dll causing error net::ERR_NAME_NOT_RESOLVED.
I was able to fix it by adding a "/" to path in request.js.
`path: "/ShippingAPI.dll?${qs}"`

Also on your example
`
usps.verify({
  Address1: '322 3rd st.',
  Address2: 'Apt 2',
  City: 'San Francisco',
  State: 'CA',
  Zip: '94103'
}).then(address => {
  console.log(address);
});
`
You have Zip but it only accepts Zip5 and Zip4 Options, This one is no big deal just letting you know.

@Sparticuz Thanks for updating and adding promises

**Comment by Sparticuz** [comment]
Ah thanks for letting me know. I'll fix the Zip. (I moved from using Zip to just parsing out Zip4 and Zip5 in the last version).

Interesting on the slash, I'm not seeing the same problem, what version of node are you using? https://github.com/Sparticuz/usps-webtools-promise/blob/eed6f878b6fbd0edc66160f25597a8642d899865/src/utils/request.ts#L111

**Comment by jgarcia24n** [comment]
I'm currently using node v12.8.1.
I think I have always used a slash on path when using https.request

**Comment by nathanaelphilip** [comment]
I received the same error. I’m on node v 13.13.0 – what’s the recommended version?

Thank you for rewriting this – it’s a wonderful package.

**Comment by Sparticuz** [comment]
It is tested on 10, 12, and 14. I just rebuilt my PC, so I haven't had time to redo my dev environment. I will definitely get to this soon though.
